api:
  location:
    host: https://restcountries.eu/rest/v2
  lokalise:
    host: https://api.lokalise.co/api2/projects/PROJECT_ID
    key: ''
  patreon:
    host: https://www.patreon.com/api/oauth2/api
    campaignId: ''
    accessToken: ''
  openCollective:
    host: https://opencollective.com/wikijs/members/all.json
  github:
    host: https://api.github.com

cache:
  ttl: 120 # minutes
  redisTTL: 86400 # seconds

cors:
  credentials: true
  maxAge: 600
  methods: 'GET,POST'
  origin: true

cron:
  hourly: 0 0 * * * *
  frequent: 0 */5 * * * *
  execOnInit: true

db:
  host: ''
  port: 0
  database: graph
  user: ''
  password: ''
  ssl: true

debug: false

port: 3000

redis:
  host: localhost
  port: 6379
  db: 0
